name = "playjonny-app-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-app.es"
HMAC_KEY = "f73b0297e3755847fc0b7ff631925bd9f4b14b69bd9ce0a45f12f49aacc4a4b1"
COOKIE_NAME = "2ar"
PLAY_PATH = "start-now"
BUTTON_ID = "p5bd2f118331d573810f542c249719fc8"
GATE_SALT = "842bc6edba338dd7"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "4cbu"
CTA_SELECTOR = ".play-button"
